In [1]:
# Question 1

import numpy as np

u = np.array([2, -7, 1])
v = np.array([-3, 0, 4])
w = np.array([0, 5, -8])

a = 3*u - 4*v
b = 2*u + 3*v - 5*w

print("a. 3u - 4v =", a)
print("b. 2u + 3v - 5w =", b)

a. 3u - 4v = [ 18 -21 -13]
b. 2u + 3v - 5w = [ -5 -39  54]


In [2]:
# Question 4

import numpy as np

A = np.array([[1, 4, -3], [6, 3, 0]])
B = np.array([[3, 2, 1], [-2, -6, -5]])
C = np.array([[2, 4], [4, 0], [-2, 2]])

alpha = 4
beta = 1/2

operations = {
    "a": lambda: A + B,
    "b": lambda: A + C,
    "c": lambda: np.transpose(B) + C,
    "d": lambda: A + np.transpose(B),
    "e": lambda: beta*C,
    "f": lambda: 4*A - 3*B,
    "g": lambda: np.transpose(A) + alpha*C,
    "h": lambda: A + B - np.transpose(C),
    "i": lambda: 4*A + 2*B - 5*np.transpose(C)
}

def performOperation(operation):
    try:
        result = operation()
    except ValueError as e:
        result = None
    return result

def print_result(result, operation_name):
    if result is not None:
        print(f"{operation_name}:")
        print(result)
        print()
    else:
        print(f"{operation_name}: Operation does not exist.")
        print()

for operation_name, operation in operations.items():
    result = performOperation(operation)
    print_result(result, operation_name)

a:
[[ 4  6 -2]
 [ 4 -3 -5]]

b: Operation does not exist.

c:
[[ 5  2]
 [ 6 -6]
 [-1 -3]]

d: Operation does not exist.

e:
[[ 1.  2.]
 [ 2.  0.]
 [-1.  1.]]

f:
[[ -5  10 -15]
 [ 30  30  15]]

g:
[[  9  22]
 [ 20   3]
 [-11   8]]

h:
[[ 2  2  0]
 [ 0 -3 -7]]

i:
[[  0   0   0]
 [  0   0 -20]]



In [3]:
# Question 5

import sympy as sp

A = sp.Matrix([[1, 3], [6, 2]])
B = sp.Matrix([[-2, 3, -2], [-4, -2, 1], [2, 4, 2]])

det_A = A.det()
det_B = B.det()

print("Determinant of matrix A:")
print(det_A)
print()

print("Determinant of matrix B:")
print(det_B)
print()

Determinant of matrix A:
-16

Determinant of matrix B:
70



In [4]:
# Question 8

import sympy as sp

A = sp.Matrix([[1, 0, 1], [1, 1, 1], [2, -1, 1]])
B = sp.Matrix([[1, 3, 1], [0, 2, 1], [2, 2, 1]])

if (A.det() == 0):
  print("Matrix A is singular.")
else:
  print("Inverse of matrix A:", A.inv())

if (B.det() == 0):
  print("Matrix B is singular.")
else:
  print("Inverse of matrix B:", B.inv())

Inverse of matrix A: Matrix([[-2, 1, 1], [-1, 1, 0], [3, -1, -1]])
Inverse of matrix B: Matrix([[0, -1/2, 1/2], [1, -1/2, -1/2], [-2, 2, 1]])


In [5]:
# Question 9

import sympy as sp

x1, x2, x3  = sp.symbols('x1 x2 x3')

M = sp.Matrix([[1, -1, 2], [1, 0, -2], [2, -1, -1]])
A = sp.Matrix([5, 8, -6])

if (M.det() == 0):
  print("Matrix M is singular. Question has no solution.")
else:
  solution = M.inv() * A
  print("Solution to the system of equations:")
  print(solution)

Solution to the system of equations:
Matrix([[46], [79], [19]])
